# Generated by Django 6.1 on 2026-08-13 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='directory',
            name='entity',
            field=models.CharField(choices=[('machine_model', 'Модель техники'), ('engine_model', 'Модель двигателя'), ('transmission_model', 'Модель трансмиссии'), ('drive_axle_model', 'Модель ведущего моста'), ('steering_axle_model', 'Модель управляемого моста'), ('maintenance_type', 'Вид ТО'), ('failure_node', 'Узел отказа'), ('recovery_method', 'Способ восстановления')], max_length=30),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('operating_hours', models.PositiveIntegerField()),
                ('work_order_number', models.CharField(max_length=100)),
                ('work_order_date', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='core.machine')),
                ('maintenance_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_by_organization', to='core.directory')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_by_type', to='core.directory')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_as_service_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
