# Generated by Django 6.1 on 2026-08-14 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_company_description_user_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='entity',
            field=models.CharField(choices=[('machine_model', 'Модель техники'), ('engine_model', 'Модель двигателя'), ('transmission_model', 'Модель трансмиссии'), ('drive_axle_model', 'Модель ведущего моста'), ('steering_axle_model', 'Модель управляемого моста'), ('maintenance_type', 'Вид ТО'), ('failure_node', 'Узел отказа'), ('recovery_method', 'Способ восстановления'), ('maintenance_organization', 'Организация, проводившая ТО')], max_length=30),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField()),
                ('operating_hours', models.PositiveIntegerField()),
                ('failure_description', models.TextField()),
                ('spare_parts', models.TextField(blank=True)),
                ('recovery_date', models.DateField(blank=True, null=True)),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims_by_failure_node', to='core.directory')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='core.machine')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims_by_recovery_method', to='core.directory')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims_as_service_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
